#pragma once
#ifndef __ENEMY_ANIMATION_STATE__
#define __ENEMY_ANIMATION_STATE__

enum EnemyAnimationState
{
	ENEMY_IDLE_RIGHT,
	ENEMY_IDLE_LEFT,
	ENEMY_RUN_RIGHT,
	ENEMY_RUN_LEFT,
	ENEMY_HIT_RIGHT,
	ENEMY_HIT_LEFT,
	ENEMY_BEHIT_RIGHT,
	ENEMY_BEHIT_LEFT,
	NUM_OF_ANIMATION_STATES
};

#endif 